# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_audiotest_wrappers", use_symbols = TRUE, package_name = "audiotest")

#' @docType package
#' @usage NULL
#' @useDynLib audiotest, .registration = TRUE
NULL

#' @export
load <- function(fname, mono, offset, duration) .Call(wrap__load, fname, mono, offset, duration)

#' @export
get_samplerate <- function(fname) .Call(wrap__get_samplerate, fname)

#' @export
play <- function(r_arr, sr) invisible(.Call(wrap__play, r_arr, sr))

test_in_R <- function() invisible(.Call(wrap__test_in_R))

